import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen">
         {children}

        </main>

        <footer className="bg-gray-800 py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-wrap justify-center items-center gap-6 text-sm text-gray-400">
            <a href="#privacy" className="hover:text-purple-400 transition-colors">
              Privacy Policy
            </a>
            <a href="#terms" className="hover:text-purple-400 transition-colors">
              Terms of Service
            </a>
            <a href="#contact" className="hover:text-purple-400 transition-colors">
              Contact Us
            </a>
            <p>© 2025 Admine. All rights reserved.</p>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}
