import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { div, main } from "framer-motion/m";
import Sidebar from "../_components/sidebare";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by khalid",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <div className="flex text-white ">
    <Sidebar />
    <main className="flex-1 ">{children}</main>
  </div>
  );
}
